api_methods:
  'default':
    0: get
    1: post
    2: put
    3: delete
  '/api/books/?':
    0: get
    1: post
  '/api/books/{id}/?':
    0: get
    1: put
    2: delete
default_api_format: json

# ENABLE DEVELOPER MODE
developer_mode: true